# Generated by Django 4.0.2 on 2022-02-01 15:40

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.avatarImage)),
            ],
        ),
    ]
