# Generated by Django 4.0.2 on 2022-02-13 19:53

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('selling', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.imageUpload)),
            ],
        ),
    ]
